'use strict'

const assert = require('assert')
const fizzBuzz = require('.')

assert(fizzBuzz(1) === 1)
assert(fizzBuzz(2) === 2)
assert(fizzBuzz(3) === 'Fizz')
assert(fizzBuzz(4) === 4)
assert(fizzBuzz(5) === 'Buzz')
assert(fizzBuzz(6) === 'Fizz')
assert(fizzBuzz(7) === 7)
assert(fizzBuzz(8) === 8)
assert(fizzBuzz(9) === 'Fizz')
assert(fizzBuzz(10) === 'Buzz')
assert(fizzBuzz(11) === 11)
assert(fizzBuzz(12) === 'Fizz')
assert(fizzBuzz(13) === 13)
assert(fizzBuzz(14) === 14)
assert(fizzBuzz(15) === 'Fizz Buzz')
assert(fizzBuzz(16) === 16)
assert(fizzBuzz(17) === 17)
assert(fizzBuzz(18) === 'Fizz')
assert(fizzBuzz(19) === 19)
assert(fizzBuzz(20) === 'Buzz')
assert(fizzBuzz(21) === 'Fizz')
assert(fizzBuzz(22) === 22)
assert(fizzBuzz(23) === 23)
assert(fizzBuzz(24) === 'Fizz')
assert(fizzBuzz(25) === 'Buzz')
assert(fizzBuzz(26) === 26)
assert(fizzBuzz(27) === 'Fizz')
assert(fizzBuzz(28) === 28)
assert(fizzBuzz(29) === 29)
assert(fizzBuzz(30) === 'Fizz Buzz')
assert(fizzBuzz(31) === 31)
assert(fizzBuzz(32) === 32)
assert(fizzBuzz(33) === 'Fizz')
assert(fizzBuzz(34) === 34)
assert(fizzBuzz(35) === 'Buzz')
assert(fizzBuzz(36) === 'Fizz')

for (let i = 1; i < 101; ++i){
    console.log(`${i} ${fizzBuzz(i)}`)
}
